/*
 * Copyright 2011 Alex K.
 *
 * This file is part of AgileWiki and is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License (LGPL) as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This code is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 * or navigate to the following url http://www.gnu.org/licenses/lgpl-2.1.txt
 *
 * Note however that only Scala, Java and JavaScript files are being covered by LGPL. 
 * All other files are covered by the Common Public License (CPL). 
 * A copy of this license is also included and can be
 * found as well at http://www.opensource.org/licenses/cpl1.0.txt
 */
package org.agilewiki
package core

import batch._
import elements.root._
import org.agilewiki.kernel._
import element.{HomogeniousINodeElement, HomogeniousBTreeElement, OrderedElement, TreeMapElement}
import org.agilewiki.kernel.element.operation.ElementConfig

import java.util.Properties
import kernel.jits.RolonJitLinkElement
import rel.ObjectLink
import util.jit.{JitNamedNakedJitTreeMap, JitConfig}

object ConfigCore {
  val NAME = "Core"
  val VERSION = "1.0"

  def apply(properties: Properties) = {
    if (properties.get(NAME) == null) {
      ConfigKernel(properties)
      properties.put(NAME, VERSION)
      init(properties)
    }
    VERSION
  }

  def init(properties: Properties) {
    new JitConfig(properties) {

      role(NAKED_OBJECT_ROLE_NAME)
      jitClass(classOf[JitNamedNakedJitTreeMap] getName)
      jitSubRole(OBJECT_LINKS_ROLE_NAME)

      role(NAKED_SUBJECT_LINKS_MAP_ROLE_NAME)
      jitClass(classOf[JitNamedNakedJitTreeMap] getName)
      jitSubRole(SUBJECT_LINK_ROLE_NAME)

      role(NAKED_SUBJECTS_MAP_ROLE_NAME)
      jitClass(classOf[JitNamedNakedJitTreeMap] getName)
      jitSubRole(SUBJECT_LINKS_ROLE_NAME)

      role(OBJECT_LINK_ROLE_NAME)
      jitClass(classOf[ObjectLink] getName)

      role(SUBJECT_LINK_ROLE_NAME)
      jitClass(classOf[RolonJitLinkElement] getName)
    }

    new ElementConfig(properties) {
      role(CREATE_ACTION_ROLE_NAME)
      kernelElementType(classOf[TreeMapElement] getName)
      include(ELEMENT_ROLE_NAME)
      op(new CreateAction)
      op(new CreatePreValidate)

      role(DELETE_ACTION_ROLE_NAME)
      kernelElementType(classOf[TreeMapElement] getName)
      include(ELEMENT_ROLE_NAME)
      op(new DeleteAction)
      op(new DeletePreValidate)

      role(OBJECT_LINKS_ROLE_NAME)
      kernelElementType(classOf[OrderedElement] getName)
      include(ORDERED_ELEMENT_ROLE_NAME)

      role(OBJECTS_ROLE_NAME)
      kernelElementType(classOf[HomogeniousBTreeElement] getName)
      jitSubRole(OBJECT_LINKS_ROLE_NAME)
      inode(OBJECTS_INODE_ELEMENT_ROLE_NAME)
      map(NAKED_OBJECT_ROLE_NAME)
      include(BTREE_ELEMENT_ROLE_NAME)

      role(OBJECTS_INODE_ELEMENT_ROLE_NAME)
      kernelElementType(classOf[HomogeniousINodeElement] getName)
      jitSubRole(OBJECT_LINKS_ROLE_NAME)
      inode(OBJECTS_INODE_ELEMENT_ROLE_NAME)
      map(NAKED_OBJECT_ROLE_NAME)
      include(ELEMENT_ROLE_NAME)

      role(ROLON_ROOT_ELEMENT_ROLE_NAME)
      op(new CoreDeleting)

      role(SUBJECT_LINKS_ROLE_NAME)
      kernelElementType(classOf[HomogeniousBTreeElement] getName)
      jitSubRole(SUBJECT_LINK_ROLE_NAME)
      inode(SUBJECT_LINKS_INODE_ELEMENT_ROLE_NAME)
      map(NAKED_SUBJECT_LINKS_MAP_ROLE_NAME)
      include(BTREE_ELEMENT_ROLE_NAME)

      role(SUBJECT_LINKS_INODE_ELEMENT_ROLE_NAME)
      kernelElementType(classOf[HomogeniousINodeElement] getName)
      jitSubRole(SUBJECT_LINK_ROLE_NAME)
      inode(SUBJECT_LINKS_INODE_ELEMENT_ROLE_NAME)
      map(NAKED_SUBJECT_LINKS_MAP_ROLE_NAME)
      include(ELEMENT_ROLE_NAME)

      role(SUBJECTS_ROLE_NAME)
      kernelElementType(classOf[HomogeniousBTreeElement] getName)
      jitSubRole(SUBJECT_LINKS_ROLE_NAME)
      inode(SUBJECTS_INODE_ELEMENT_ROLE_NAME)
      map(NAKED_SUBJECTS_MAP_ROLE_NAME)
      include(BTREE_ELEMENT_ROLE_NAME)

      role(SUBJECTS_INODE_ELEMENT_ROLE_NAME)
      kernelElementType(classOf[HomogeniousINodeElement] getName)
      jitSubRole(SUBJECT_LINKS_ROLE_NAME)
      inode(SUBJECTS_INODE_ELEMENT_ROLE_NAME)
      map(NAKED_SUBJECTS_MAP_ROLE_NAME)
      include(ELEMENT_ROLE_NAME)

      role(UPDATE_ACTION_ROLE_NAME)
      kernelElementType(classOf[TreeMapElement] getName)
      include(ELEMENT_ROLE_NAME)
      op(new UpdateAction)
      op(new UpdatePreValidate)
    }

    new CConfig(properties) {
      role(CoreNames.ACCESS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.GROUP_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.GROUPS_TYPE)
      subj(CoreNames.ACCESS_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.REALM_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      subj(CoreNames.REALM_CHANGE_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      subj(CoreNames.REALM_HEADLINES_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.ACCESS_TYPE, CoreNames.GROUPS_TYPE, CoreNames.ACCESS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.ACCESS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.ACCESS_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.ADMIN_GROUP_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.GROUP_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.GROUPS_TYPE)
      subj(CoreNames.ACCESS_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.MEMBER_RELATIONSHIP, CoreNames.USER_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.REALM_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      subj(CoreNames.REALM_HEADLINES_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      subj(CoreNames.REALM_CHANGE_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.ADMIN_GROUP_TYPE, CoreNames.GROUPS_TYPE, CoreNames.ADMIN_GROUP_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.ADMIN_GROUP_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.ADMIN_GROUP_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.ADMIN_USER_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.USER_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.USERS_TYPE)
      subj(CoreNames.ACCESS_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.LIMIT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.MEMBER_RELATIONSHIP, CoreNames.MY_GROUP_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.REALM_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      subj(CoreNames.REALM_HEADLINES_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      subj(CoreNames.REALM_CHANGE_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.ADMIN_USER_TYPE, CoreNames.USERS_TYPE, CoreNames.ADMIN_USER_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.ADMIN_USER_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.ADMIN_USER_TYPE, CoreNames.ADMIN_USER_TYPE, "owner")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.ADMIN_USER_TYPE, KernelNames.HOME_TYPE, " ")
      rel(CoreNames.MEMBER_RELATIONSHIP, CoreNames.ADMIN_USER_TYPE, CoreNames.ADMIN_GROUP_TYPE, "owner")

      role(CoreNames.ANONYMOUS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.USER_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.USERS_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      subj(CoreNames.ACCESS_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.LIMIT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.MEMBER_RELATIONSHIP, CoreNames.MY_GROUP_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.REALM_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      subj(CoreNames.REALM_HEADLINES_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      subj(CoreNames.REALM_CHANGE_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.ANONYMOUS_TYPE, CoreNames.USERS_TYPE, CoreNames.ANONYMOUS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.ANONYMOUS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.ANONYMOUS_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.AUTHORITY_TYPE)
      include(CoreNames.PAGE_TYPE)

      role(CoreNames.BASE_GROUPS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.PAGE_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, CoreNames.MY_GROUP_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)

      role(CoreNames.BATCH_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(KernelNames.CHANGE_TYPE)
      op(new BatchJE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.USER_RELATIONSHIP, CoreNames.USER_TYPE)
      obj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.COMMAND_TYPE)
      obj(CoreNames.EFFECTS_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_CHANGE_RELATIONSHIP, CoreNames.REALM_TYPE)

      role(CoreNames.COMMAND_TYPE)
      include(CoreNames.PAGE_TYPE)

      role(CoreNames.COMMANDS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(KernelNames.PAGE_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE, KernelNames.HOME_TYPE, CoreNames.COMMANDS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.COMMANDS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.COMMANDS_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.CORE_INITIALIZATION_CHANGE_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(KernelNames.INITIALIZATION_CHANGE_TYPE)
      op(new CoreInitializationJE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)

      role(CoreNames.CREATE_GROUP_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.CREATE_GROUP_TYPE, CoreNames.COMMANDS_TYPE,
        CoreNames.CREATE_GROUP_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.CREATE_GROUP_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.CREATE_GROUP_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.CREATE_GROUPS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.CREATE_GROUPS_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.CREATE_GROUPS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.CREATE_GROUPS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.CREATE_GROUPS_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.CREATE_MY_GROUP_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.CREATE_MY_GROUP_TYPE, CoreNames.COMMANDS_TYPE,
        CoreNames.CREATE_MY_GROUP_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.CREATE_MY_GROUP_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.CREATE_MY_GROUP_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.CREATE_SUBTOPIC_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.CREATE_SUBTOPIC_TYPE, CoreNames.COMMANDS_TYPE,
        CoreNames.CREATE_SUBTOPIC_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.CREATE_SUBTOPIC_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.CREATE_SUBTOPIC_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.CREATE_SUBTOPICS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.CREATE_SUBTOPICS_TYPE, CoreNames.COMMANDS_TYPE,
        CoreNames.CREATE_SUBTOPICS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.CREATE_SUBTOPICS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.CREATE_SUBTOPICS_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.DELETE_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.DELETE_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.DELETE_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.DELETE_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.DELETE_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.EDIT_MEMBERSHIP_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.EDIT_MEMBERSHIP_TYPE, CoreNames.COMMANDS_TYPE,
        CoreNames.EDIT_MEMBERSHIP_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.EDIT_MEMBERSHIP_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.EDIT_MEMBERSHIP_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.EDIT_GROUP_ACCESS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.EDIT_GROUP_ACCESS_TYPE, CoreNames.COMMANDS_TYPE,
        CoreNames.EDIT_GROUP_ACCESS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.EDIT_GROUP_ACCESS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.EDIT_GROUP_ACCESS_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.EDIT_SUBTOPICS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.EDIT_SUBTOPICS_TYPE, CoreNames.COMMANDS_TYPE,
        CoreNames.EDIT_SUBTOPICS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.EDIT_SUBTOPICS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.EDIT_SUBTOPICS_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.EDIT_TEXT_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.EDIT_TEXT_TYPE, CoreNames.COMMANDS_TYPE,
        CoreNames.EDIT_TEXT_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.EDIT_TEXT_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.EDIT_TEXT_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.EDIT_USER_ACCESS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.EDIT_USER_ACCESS_TYPE, CoreNames.COMMANDS_TYPE,
        CoreNames.EDIT_USER_ACCESS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.EDIT_USER_ACCESS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.EDIT_USER_ACCESS_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.EDIT_USER_LIMITS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.EDIT_USER_LIMITS_TYPE, CoreNames.COMMANDS_TYPE,
        CoreNames.EDIT_USER_LIMITS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.EDIT_USER_LIMITS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.EDIT_USER_LIMITS_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.GROUP_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.MY_GROUP_TYPE)
      include(CoreNames.REALM_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.GROUPS_TYPE)
      subj(CoreNames.ACCESS_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.MEMBER_RELATIONSHIP, CoreNames.USER_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.REALM_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      subj(CoreNames.REALM_CHANGE_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      subj(CoreNames.REALM_HEADLINES_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)

      role(CoreNames.GROUPS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.BASE_GROUPS_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, CoreNames.GROUP_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.GROUPS_TYPE, KernelNames.HOME_TYPE, CoreNames.GROUPS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.GROUPS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.GROUPS_TYPE, KernelNames.HOME_TYPE, " ")

      role(KernelNames.HOME_TYPE) //see ConfigKernel
      include(CoreNames.REALM_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.REALM_RELATIONSHIP, KernelNames.PAGE_TYPE)
      rel(CoreNames.ACCESS_RELATIONSHIP, KernelNames.HOME_TYPE, CoreNames.ACCESS_TYPE, "reader")
      subj(CoreNames.REALM_CHANGE_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.PAGE_TYPE)
      subj(CoreNames.REALM_HEADLINES_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)

      role(CoreNames.LOGON_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.LOGON_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.LOGON_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.LOGON_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.LOGON_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.LOGOFF_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.LOGOFF_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.LOGOFF_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.LOGOFF_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.LOGOFF_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.MY_GROUP_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.BASE_GROUPS_TYPE)
      subj(CoreNames.ACCESS_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.MEMBER_RELATIONSHIP, CoreNames.USER_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)

      role(CoreNames.ORDER_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.ORDER_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.ORDER_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.ORDER_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.ORDER_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.PASSWORD_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.PASSWORD_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.PASSWORD_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.PASSWORD_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.PASSWORD_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.RENAME_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.RENAME_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.RENAME_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.RENAME_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.RENAME_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.SET_PASSWORD_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.SET_PASSWORD_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.SET_PASSWORD_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.SET_PASSWORD_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.SET_PASSWORD_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.SUBTOPIC_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(KernelNames.PAGE_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.SUBTOPICS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      subj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.PAGE_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)

      role(CoreNames.SUBTOPICS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(KernelNames.PAGE_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)

      role(CoreNames.TAGLINE_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.TAGLINE_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.TAGLINE_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.TAGLINE_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.TAGLINE_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.TIMEZONE_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.TIMEZONE_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.TIMEZONE_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.TIMEZONE_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.TIMEZONE_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.NEW_USER_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.COMMAND_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.COMMANDS_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.COMMAND_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.NEW_USER_TYPE, CoreNames.COMMANDS_TYPE, CoreNames.NEW_USER_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.NEW_USER_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.NEW_USER_TYPE, KernelNames.HOME_TYPE, " ")

      role(KernelNames.PAGE_TYPE) //see ConfigKernel
      obj(CoreNames.PARENT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)

      role(CoreNames.REALM_TYPE)
      include(KernelNames.PAGE_TYPE)

      role(CoreNames.SYSTEM_USER_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.USER_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.USERS_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      subj(CoreNames.ACCESS_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.LIMIT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.MEMBER_RELATIONSHIP, CoreNames.MY_GROUP_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.REALM_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      subj(CoreNames.REALM_HEADLINES_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      subj(CoreNames.REALM_CHANGE_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.SYSTEM_USER_TYPE, CoreNames.USERS_TYPE, CoreNames.SYSTEM_USER_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.SYSTEM_USER_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.SYSTEM_USER_TYPE, KernelNames.HOME_TYPE, " ")

      role(CoreNames.USER_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(CoreNames.REALM_TYPE)
      include(CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, CoreNames.USERS_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      subj(CoreNames.ACCESS_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.LIMIT_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.MEMBER_RELATIONSHIP, CoreNames.MY_GROUP_TYPE)
      subj(CoreNames.USER_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      subj(CoreNames.REALM_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      subj(CoreNames.REALM_CHANGE_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.ALL_HEADLINES_RELATIONSHIP, KernelNames.HOME_TYPE)
      subj(CoreNames.REALM_HEADLINES_RELATIONSHIP, KernelNames.PAGE_TYPE)
      obj(CoreNames.REALM_HEADLINES_RELATIONSHIP, CoreNames.REALM_TYPE)
      obj(CoreNames.SUBTOPIC_RELATIONSHIP, CoreNames.SUBTOPIC_TYPE)

      role(CoreNames.USERS_TYPE)
      rootElementType(ROLON_ROOT_ELEMENT_ROLE_NAME)
      include(KernelNames.PAGE_TYPE)
      subj(CoreNames.PARENT_RELATIONSHIP, CoreNames.USER_TYPE)
      obj(CoreNames.PARENT_RELATIONSHIP, KernelNames.HOME_TYPE)
      obj(CoreNames.ACCESS_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      obj(CoreNames.LIMIT_RELATIONSHIP, CoreNames.AUTHORITY_TYPE)
      subj(CoreNames.EFFECTS_RELATIONSHIP, CoreNames.BATCH_TYPE)
      obj(CoreNames.REALM_RELATIONSHIP, CoreNames.REALM_TYPE)
      rel(CoreNames.PARENT_RELATIONSHIP, CoreNames.USERS_TYPE, KernelNames.HOME_TYPE, CoreNames.USERS_NAME)
      rel(CoreNames.ACCESS_RELATIONSHIP, CoreNames.USERS_TYPE, CoreNames.ACCESS_TYPE, "reader")
      rel(CoreNames.REALM_RELATIONSHIP, CoreNames.USERS_TYPE, KernelNames.HOME_TYPE, " ")
    }
  }
}
