def extendedContext = context.getSpecial(".extendedContext")
def loopPrefix = context.get("loopPrefix")
if (loopPrefix.length() > 0)
  loopPrefix = loopPrefix+"."
def timestamp = context.get("timestamp")
def rolonUuid = context.get(loopPrefix+"rolonUuid")
def relType = context.relationshipName(context.get(loopPrefix+"relType"))
def subjectKeysSequence = extendedContext.subjectKeysSequence(timestamp,rolonUuid, relType)
def contextFilterSequence = extendedContext.contextFilterSequence(context,subjectKeysSequence,"subjectKeys")
context.setSpecial(loopPrefix+"sequence",contextFilterSequence)
context.setCon(loopPrefix+"isUuidSequence","true")
